name: Linting & Scanning

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'infra/**'

jobs:
  flake8-lint:
    # strategy:
    #   matrix:
    #     python-version: [3.11]
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout Main
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install SqlFluff
        run: "pip install sqlfluff==2.0.3"

      - name: Install boto3
        run: "pip install boto3"

      - name: SqlFluff Linting
        run: |
          find . -type f -name "*.sql" -exec sqlfluff lint --dialect mysql {} \;

      # - name: Locate and Run Tests
      #   run: python -m unittest discover ./tests

      # - name: flake8 Lint
      #   uses: py-actions/flake8@v2